// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"database/sql"
	"time"
)

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID        uint32       `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name      string       `gorm:"column:name;not null" json:"name"`
	Age       uint32       `gorm:"column:age;not null" json:"age"`
	Gender    uint32       `gorm:"column:gender;not null" json:"gender"`
	Birthday  sql.NullTime `gorm:"column:birthday" json:"birthday"`
	CreatedAt time.Time    `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt time.Time    `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
