// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package api

import (
	"gorm.io/gen"
	"helloworld/dal/query"
	"helloworld/internal/conf"
	"helloworld/internal/controller"
	"helloworld/internal/pkg/store"
	"helloworld/internal/repository"
	"helloworld/internal/service"
)

// Injectors from wire.go:

func wireApp(server *conf.Server, config store.Config, arg ...gen.DOOption) (*APP, func(), error) {
	db, cleanup, err := store.NewMySQL(config)
	if err != nil {
		return nil, nil, err
	}
	queryQuery := query.Use(db, arg...)
	userInter := repository.NewUserInter(queryQuery)
	userSrv := service.NewUserSrv(userInter)
	handler := controller.NewHandler(userSrv)
	greeterInter := repository.NewGreeterInter(queryQuery)
	greeterSrv := service.NewGreeterSrv(greeterInter, userInter)
	app := newApp(server, handler, greeterSrv, userSrv)
	return app, func() {
		cleanup()
	}, nil
}
