// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package api

import (
	"git.xq5.com/golang/helloworld/dal/query"
	"git.xq5.com/golang/helloworld/internal/conf"
	"git.xq5.com/golang/helloworld/internal/controller"
	"git.xq5.com/golang/helloworld/internal/pkg/store"
	"git.xq5.com/golang/helloworld/internal/repository"
	"git.xq5.com/golang/helloworld/internal/service"
	"gorm.io/gen"
)

// Injectors from wire.go:

func wireApp(server *conf.Server, session *conf.Session, config store.Config, arg ...gen.DOOption) (*APP, func(), error) {
	db, cleanup, err := store.NewMySQL(config)
	if err != nil {
		return nil, nil, err
	}
	queryQuery := query.Use(db, arg...)
	greeterInter := repository.NewGreeterInter(queryQuery)
	userInter := repository.NewUserInter(queryQuery)
	greeterSrv := service.NewGreeterSrv(greeterInter, userInter)
	userSrv := service.NewUserSrv(userInter, session)
	serviceService := service.NewService(greeterSrv, userSrv)
	handler := controller.NewHandler(serviceService, session)
	app := newApp(server, handler, serviceService)
	return app, func() {
		cleanup()
	}, nil
}
